AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: >
  sam

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Tracing: Active

Parameters:
  AppName:
    Type: String
    Default: app-financiera
  AppEnv:
    Type: String
    Default: dev

Resources:
  # ------------- IAM Role -------------
  AppFinancieraRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AppName}-role-${AppEnv}
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: 2012-10-17
      Policies:
        - PolicyName: AppFinancieraLogsPolicy
          PolicyDocument:
            Statement:
              - Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Effect: Allow
                Resource: "*"
            Version: 2012-10-17
        - PolicyName: AppFinancieraDynamoDBPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - dynamodb:BatchGetItem
                  - dynamodb:GetItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:BatchWriteItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                Effect: Allow
                Resource:
                  - !GetAtt AppFinancieraTable.Arn
        - PolicyName: AppNameS3Policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:DeleteObject
                Effect: Allow
                Resource:
                  - !GetAtt AppFinancieraBucket.Arn
                  - !Sub ${AppFinancieraBucket.Arn}/*

  # ------------- API Gateway -------------
  AppFinancieraApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Sub ${AppEnv}

  # ------------- DynamoDB -------------
  AppFinancieraTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AppName}-table-${AppEnv}
      AttributeDefinitions:
        - AttributeName: usuario
          AttributeType: S
      KeySchema:
        - AttributeName: usuario
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  # ------------- S3 -------------
  AppFinancieraBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AppName}-bucket-${AppEnv}
      AccessControl: Private

  # ------------- Lambda functions -------------
  AppFinancieraFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AppName}-function-${AppEnv}
      CodeUri: src/source-code/
      Handler: app.handler
      Role: !GetAtt AppFinancieraRole.Arn
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          CORS_ORIGIN: "*"
          DYNAMODB_TABLE: !Ref AppFinancieraTable
          S3_BUCKET: !Ref AppFinancieraBucket
      Events:
        AppFinancieraFunctionProxy:
          Type: Api
          Properties:
            RestApiId: !Ref AppFinancieraApiGateway
            Method: ANY
            Path: /{proxy+}

Outputs:
  AppFinancieraApiGateway:
    Description: API Gateway endpoint URL
    Value: !Sub https://${AppFinancieraApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${AppEnv}/
